server:
  port: 6666
spring:
  redis:
    host: 192.168.109.4
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.109.4:1111
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - ValidateCodeFilter
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/api/admin/**



kaptcha:
  #是否有边框，默认为yes，可选yes、no
  border: "yes"
  #//边框颜色
  border.color: 105,179,90
  textproducer:
    font:
      #验证码字体颜色
      color: blue
      #文本字符大小
      size: 30
      #文本字体样式
      names: 宋体,楷体,微软雅黑
    char:
      #验证码文本字符长度
      length: 4
  image:
    #图片宽度
    width: 120
    #图片高度
    height: 40
  session:
    #存储session key
    key: code