server:
  port: 2001
spring:
  application:
    name: service-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.109.4:1111
        username: nacos
        password: nacos
